# Generated by tools/vendor_fa4.py from quack-kernels 0.6.5
# (Apache-2.0, see LICENSE). Do not edit.
"""Compatibility tombstone for the removed QuACK trace API."""

raise ImportError(
    "quack.trace has been removed. QuACK now uses NVIDIA IKET directly; import "
    "`cutlass.cute.experimental.iket` and run workloads under "
    "`python -m iket.cli.main ... profile -- ...`. See "
    "`examples/example_iket_trace.py` for a minimal marker workload and "
    "`examples/example_gemm_trace.py` for a real GEMM trace."
)
