# Generated by tools/vendor_fa4.py from quack-kernels 0.6.5
# (Apache-2.0, see LICENSE). Do not edit.
# Copyright (c) 2025-2026, Tri Dao.

"""Spec-layer helpers for TensorSpec, TMA descriptors, and TMEM layouts."""
