# Generated by tools/vendor_fa4.py from quack-kernels 0.6.5
# (Apache-2.0, see LICENSE). Do not edit.
# Copyright (c) 2025, Wentao Guo, Ted Zadouri, Tri Dao.

"""CuTe DSL helpers and integration hooks."""

from ..dsl import cute_tensor_indexing  # noqa: F401
from ..dsl import cute_tensor  # noqa: F401
from ..dsl import mixed_constexpr_if  # noqa: F401
from ..dsl.torch_library_op import cute_op

__all__ = ["cute_op"]


def __getattr__(name: str):
    if name == "cute_op":
        from ..dsl.torch_library_op import cute_op

        return cute_op
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
