"""Regenerates the private FlashAttention-4 copies in veda_comfy/_vendor.

    python tools/vendor_fa4.py            # rewrite veda_comfy/_vendor
    python tools/vendor_fa4.py --check    # verify the committed copies

Two copies are generated from the pinned FA4 wheel, never edited by hand:

  fa4_upstream  unmodified FA4 (SM90 / SM100 backends)
  fa4_sm8x      FA4 + Miowtion's SM8x / SM120 block-sparse patch series
                (tools/fa4_patches/sm8x, applied with `git apply`;
                SM80-family and SM120 backends)

Both get the same two mechanical changes:
  1. `flash_attn.cute` imports are rewritten to relative ones, so each copy
     is a private package: no global `flash_attn` import, no clash with
     another custom node's FlashAttention, no import-order dependency.
  2. Small compatibility edits (COMPAT_EDITS), each of which must match
     exactly once or the tool fails. Today: FA4 imports `fcntl` at module
     scope (Linux-only) for its opt-in persistent JIT cache; on Windows the
     import becomes optional and that cache runs without file locks.

Every input is pinned by sha256 (wheel, upstream files the patches touch,
patched results), so a regeneration is reproducible and an upstream change
cannot slip in silently. Needs `git` on PATH (for `git apply`).
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import urllib.request
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VENDOR = os.path.join(ROOT, 'veda_comfy', '_vendor')
PATCHES = os.path.join(ROOT, 'tools', 'fa4_patches', 'sm8x')

FA4_VERSION = '4.0.0b32'
FA4_WHEEL = ('https://files.pythonhosted.org/packages/40/d0/'
             'b1e9ab8eefc9e67179a372c3e1a8e9f83d963c3a8e5bd4c738e55dd134c0/'
             'flash_attn_4-4.0.0b32-py3-none-any.whl')
FA4_WHEEL_SHA256 = ('9299da3524d579d84eb92954d3243aa095d55ebdafcf80d6a9766fd9'
                    '6fe8a562')
_PKG = 'flash_attn/cute/'

# Upstream files the patch series modifies, and the patched results, as
# pinned by Miowtion (miowtion/kernels/fa4_sm8x/__init__.py and its
# vendored files). sha256 before import rewriting / compat edits.
UPSTREAM_SHA256 = {
    'block_sparsity.py':
        '9331cb2abd4be4da87a74c0839b665d5f914ac6f51cb97491e97b26199668ac9',
    'block_sparse_utils.py':
        '608f6c5a1c68daadfca402ec1259917019a195dc748ce9f24b92f0551d2ff6ba',
    'flash_fwd.py':
        'be6e88c7d9f122aa5ab29ff5946f6270af0b580e4403351b869f1330b71ca53c',
    'flash_bwd.py':
        '80cb6bfb436160d73b7214529f94d28b7333c98dff75a53d20552eb33645fea2',
    'interface.py':
        '144a3dd6f72f955e43834500808c7d47b3b4a76fdcd0b7188f9b459d85007cab',
    # Not patched, but SM120 block sparsity relies on these being thin
    # subclasses of the patched SM80 kernels.
    'flash_fwd_sm120.py':
        'abd017add69914e46f0fcfc017ad51c3d07d79fd87d15f969036ddd82bcc7da2',
    'flash_bwd_sm120.py':
        'ad2d802c97dbf654fd03724bcfa91702b18acec8518e5dd4a33f137ba238bf7d',
}
PATCHED_SHA256 = {
    'block_sparsity.py':
        '9b539633f15a8475c873dfff30ee7090144b466cc6bed4665c6149c0c7d66cdf',
    'block_sparse_utils.py':
        '69b7a955e7a7cb756b0b475241e771feba7497670b570dd5ddb279e2b51ac7ad',
    'flash_fwd.py':
        'a2e543e5a35f20747df059f692210791047f36af8cf483b788f79cef543c4fdc',
    'flash_bwd.py':
        '0d7fffb59e3013d0e24172f7c897f9a0fec71549c62ed1b1b29e19358b33038c',
    'interface.py':
        '2db27ac666538a74c598f6c3feccf9b0969a7d1db9941947a8bea1ecef0acab2',
}

COMPAT_EDITS = [
    ('cache_utils.py',
     'import fcntl\n',
     'try:\n'
     '    import fcntl\n'
     'except ImportError:  # veda: Windows has no fcntl; the opt-in\n'
     '    fcntl = None  # persistent JIT cache then runs without file locks\n'),
    ('cache_utils.py',
     '    def __enter__(self) -> "FileLock":\n',
     '    def __enter__(self) -> "FileLock":\n'
     '        if fcntl is None:  # veda: Windows, no advisory locks\n'
     '            return self\n'),
    ('cache_utils.py',
     '        if self._fd is not None:\n'
     '            fcntl.flock(self._fd, fcntl.LOCK_UN)\n',
     '        if fcntl is not None and self._fd is not None:\n'
     '            fcntl.flock(self._fd, fcntl.LOCK_UN)\n'),
]

_IMPORT_RULES = [
    (re.compile(r'^(\s*)from flash_attn\.cute import '), r'\1from . import '),
    (re.compile(r'^(\s*)from flash_attn\.cute\.([\w.]+) import '),
     r'\1from .\2 import '),
    (re.compile(r'^(\s*)import flash_attn\.cute\.(\w+) as (\w+)(\s*)$'),
     r'\1from . import \2 as \3\4'),
]
_LEFTOVER = re.compile(r'^\s*(from|import)\s+flash_attn\b')

HEADER = ('# Generated by tools/vendor_fa4.py from FlashAttention-4 '
          f'{FA4_VERSION}\n# (BSD-3-Clause, see LICENSE). Do not edit.\n')


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _wheel(path: str | None) -> bytes:
    if path:
        with open(path, 'rb') as f:
            data = f.read()
    else:
        print(f'downloading FA4 {FA4_VERSION} wheel ...', flush=True)
        with urllib.request.urlopen(FA4_WHEEL, timeout=120) as response:
            data = response.read()
    if _sha256(data) != FA4_WHEEL_SHA256:
        sys.exit('FA4 wheel sha256 mismatch: refusing to vendor')
    return data


def _sources(wheel: bytes) -> tuple[dict[str, bytes], dict[str, bytes]]:
    """(flash_attn/cute *.py files, license files) from the wheel."""
    files, licenses = {}, {}
    with zipfile.ZipFile(io.BytesIO(wheel)) as archive:
        for name in archive.namelist():
            if name.startswith(_PKG) and name.endswith('.py'):
                rel = name[len(_PKG):]
                if '/' in rel:
                    sys.exit(f'unexpected subpackage in FA4: {name}')
                files[rel] = archive.read(name)
            elif '/licenses/' in name:
                licenses[os.path.basename(name)] = archive.read(name)
    for rel, digest in UPSTREAM_SHA256.items():
        if _sha256(files[rel]) != digest:
            sys.exit(f'upstream {rel} differs from the pinned base')
    return files, licenses


def _apply_patches(files: dict[str, bytes]) -> dict[str, bytes]:
    with tempfile.TemporaryDirectory() as tmp:
        cute = os.path.join(tmp, 'flash_attn', 'cute')
        os.makedirs(cute)
        for rel, data in files.items():
            with open(os.path.join(cute, rel), 'wb') as f:
                f.write(data)
        patches = sorted(os.path.join(PATCHES, p) for p in os.listdir(PATCHES)
                         if p.endswith('.patch'))
        subprocess.run(['git', 'apply', '--exclude=tests/*', *patches],
                       cwd=tmp, check=True)
        patched = {}
        for rel in files:
            with open(os.path.join(cute, rel), 'rb') as f:
                patched[rel] = f.read()
    for rel, digest in PATCHED_SHA256.items():
        if _sha256(patched[rel]) != digest:
            sys.exit(f'patched {rel} differs from the pinned result')
    return patched


def _rewrite(rel: str, data: bytes) -> bytes:
    text = data.decode('utf-8')
    for path, old, new in COMPAT_EDITS:
        if path == rel:
            if text.count(old) != 1:
                sys.exit(f'compat edit does not match {rel} exactly once: '
                         f'{old!r}')
            text = text.replace(old, new)
    lines = []
    for line in text.splitlines(keepends=True):
        for pattern, replacement in _IMPORT_RULES:
            line = pattern.sub(replacement, line)
        if _LEFTOVER.match(line):
            sys.exit(f'{rel}: unhandled flash_attn import: {line.strip()}')
        lines.append(line)
    return (HEADER + ''.join(lines)).encode('utf-8')


def generate(out_dir: str, wheel_path: str | None) -> None:
    files, licenses = _sources(_wheel(wheel_path))
    copies = {'fa4_upstream': files, 'fa4_sm8x': _apply_patches(files)}
    for name, sources in copies.items():
        target = os.path.join(out_dir, name)
        os.makedirs(target)
        for rel, data in sorted(sources.items()):
            with open(os.path.join(target, rel), 'wb') as f:
                f.write(_rewrite(rel, data))
        for rel, data in licenses.items():
            with open(os.path.join(target, rel), 'wb') as f:
                f.write(data)
        provenance = {
            'fa4_version': FA4_VERSION, 'wheel': FA4_WHEEL,
            'wheel_sha256': FA4_WHEEL_SHA256,
            'patches': sorted(p for p in os.listdir(PATCHES)
                              if p.endswith('.patch')) if name == 'fa4_sm8x'
            else [],
            'compat_edits': sorted({p for p, _, _ in COMPAT_EDITS}),
            'generator': 'tools/vendor_fa4.py',
        }
        with open(os.path.join(target, 'VENDORED.json'), 'w') as f:
            json.dump(provenance, f, indent=1, sort_keys=True)
            f.write('\n')


def _tree(root: str) -> dict[str, str]:
    out = {}
    for base, _, names in os.walk(root):
        if '__pycache__' in base:
            continue
        for name in names:
            path = os.path.join(base, name)
            with open(path, 'rb') as f:
                out[os.path.relpath(path, root)] = _sha256(f.read())
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    parser.add_argument('--check', action='store_true',
                        help='verify veda_comfy/_vendor instead of writing')
    parser.add_argument('--wheel', help='local FA4 wheel (else download)')
    args = parser.parse_args()
    with tempfile.TemporaryDirectory() as tmp:
        generate(tmp, args.wheel)
        names = ('fa4_upstream', 'fa4_sm8x')
        if args.check:
            for name in names:
                if _tree(os.path.join(tmp, name)) != _tree(
                        os.path.join(VENDOR, name)):
                    sys.exit(f'veda_comfy/_vendor/{name} is not what '
                             'tools/vendor_fa4.py generates; regenerate it')
            print('vendored FA4 copies are up to date')
            return
        for name in names:
            target = os.path.join(VENDOR, name)
            shutil.rmtree(target, ignore_errors=True)
            shutil.copytree(os.path.join(tmp, name), target)
        print(f'wrote {", ".join(names)} into veda_comfy/_vendor')


if __name__ == '__main__':
    main()
