"""Static checks of the vendored FA4 copies and the FA4 backends' failure
modes; runs anywhere (the kernels themselves are tested in tests/gpu)."""

import ast
import json
import os
import re

import pytest

from conftest import ROOT
from veda_comfy import hardware
from veda_comfy.backends import base
from veda_comfy.backends import fa4_sm80
from veda_comfy.backends import fa4_sm90
from veda_comfy.backends import fa4_sm100
from veda_comfy.backends import fa4_sm120

VENDOR = os.path.join(ROOT, 'veda_comfy', '_vendor')
COPIES = ('fa4_upstream', 'fa4_sm8x')
PACKAGES = COPIES + ('quack',)


def _resolves(folder, level, module, names):
    base = folder
    for _ in range(level - 1):
        base = os.path.dirname(base)
    if module:
        target = os.path.join(base, *module.split('.'))
        return os.path.isdir(target) or os.path.isfile(target + '.py')
    return all(os.path.isdir(os.path.join(base, n))
               or os.path.isfile(os.path.join(base, n + '.py'))
               or os.path.isfile(os.path.join(base, '__init__.py'))
               for n in names)


@pytest.mark.parametrize('package', PACKAGES)
def test_vendored_package_is_private_and_complete(package):
    root = os.path.join(VENDOR, package)
    files = [os.path.join(base, f) for base, _, names in os.walk(root)
             for f in names if f.endswith('.py')]
    assert files
    for path in files:
        with open(path, encoding='utf-8') as f:
            source = f.read()
        assert source.startswith('# Generated by tools/vendor_fa4.py'), path
        tree = ast.parse(source)  # every file is valid Python
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                assert not any(a.name.split('.')[0] in ('flash_attn',
                                                        'quack')
                               for a in node.names), path
            if isinstance(node, ast.ImportFrom):
                top = (node.module or '').split('.')[0]
                assert node.level or top not in ('flash_attn', 'quack'), path
                if node.level:
                    assert _resolves(os.path.dirname(path), node.level,
                                     node.module,
                                     [a.name for a in node.names]), (
                        f'{path}: {"." * node.level}{node.module}')


@pytest.mark.parametrize('path', [('fa4_upstream', 'cache_utils.py'),
                                  ('fa4_sm8x', 'cache_utils.py'),
                                  ('quack', 'cache', 'jit.py'),
                                  ('quack', 'cache', 'async_compile.py')])
def test_windows_has_no_hard_fcntl_import(path):
    with open(os.path.join(VENDOR, *path), encoding='utf-8') as f:
        source = f.read()
    assert re.search(r'^import fcntl', source, re.M) is None
    assert 'except ImportError:  # veda' in source


def test_provenance_records_the_patch_series():
    with open(os.path.join(VENDOR, 'fa4_sm8x', 'VENDORED.json')) as f:
        sm8x = json.load(f)
    with open(os.path.join(VENDOR, 'fa4_upstream', 'VENDORED.json')) as f:
        upstream = json.load(f)
    assert sm8x['version'] == upstream['version'] == '4.0.0b32'
    assert len(sm8x['patches']) == 7 and upstream['patches'] == []


def _cuda(cc, name='GPU'):
    return hardware.DeviceInfo('cuda', 0, name, cc,
                               hardware._FAMILIES.get(cc, 'x'),
                               hardware._cuda_subtype(cc, name), 'linux',
                               'x86_64', None, False, '13.0')


@pytest.mark.parametrize('module,cc', [
    (fa4_sm80, (8, 9)), (fa4_sm90, (9, 0)), (fa4_sm100, (10, 0)),
    (fa4_sm120, (12, 1))])
def test_fa4_backends_explain_missing_kernels(module, cc):
    try:
        import cutlass  # noqa: F401
        pytest.skip('cutlass is installed; covered by tests/gpu')
    except ImportError:
        pass
    with pytest.raises(base.BackendUnavailable, match='install_fa4'):
        module.create(_cuda(cc))


@pytest.mark.parametrize('module,cc', [
    (fa4_sm80, (9, 0)), (fa4_sm90, (8, 9)), (fa4_sm100, (12, 0)),
    (fa4_sm120, (10, 0))])
def test_fa4_backends_refuse_other_families(module, cc):
    with pytest.raises(base.BackendUnavailable, match='is for'):
        module.create(_cuda(cc))
