"""FA4 CuTe block-sparse attention on the SM80 family: sm80 (A100), sm86
(RTX 30, A-series workstation), sm87 (Orin), sm89 (RTX 40, L4 / L40,
RTX 6000 Ada).

Upstream FA4's SM80 kernels accept block-sparse tensors but ignore them and
compute dense attention. This backend runs the private vendored copy
`veda_comfy/_vendor/fa4_sm8x` (FA4 4.0.0b32 + Miowtion's SM8x patch series,
regenerated by `tools/vendor_fa4.py`), which adds the block-sparse main
loops and the `DenseBlockMaskTorch` input: the block mask goes to the kernel
as is, no index lists. Private copy: no global `flash_attn` import, so other
custom nodes that use FlashAttention are unaffected.

Self-contained on purpose (see backends/base.py): shares nothing with the
other FA4 backends except the vendored package, which is generated, never
edited by hand.
"""

from __future__ import annotations

import functools
import threading

import torch

from . import base
from ..core import tiling

_MAJOR = 8
# The first call of a signature JIT-compiles through CuTe DSL / MLIR, which
# is not documented as thread-safe; only the host-side launch is held.
_CALL_LOCK = threading.Lock()


@functools.cache
def _modules():
    import cutlass  # pylint: disable=import-outside-toplevel
    import cutlass.cute as cute  # pylint: disable=import-outside-toplevel
    from .._vendor.fa4_sm8x import block_sparsity  # pylint: disable=import-outside-toplevel
    from .._vendor.fa4_sm8x import interface  # pylint: disable=import-outside-toplevel
    from .._vendor.fa4_sm8x import utils  # pylint: disable=import-outside-toplevel
    return cutlass, cute, block_sparsity, interface, utils


@functools.cache
def _valid_key_mask_mod():
    """The singleton mask_mod: key slot n is real iff aux_tensors[0][n] != 0.

    A module-level singleton because FA4 keys its compile cache on the
    callable; a fresh closure per call would recompile every call.
    """
    cutlass, cute, _, _, utils = _modules()

    @cute.jit
    def valid_key(batch, head, m_idx, n_idx, seqlen_info, aux_tensors):
        del batch, head, m_idx, seqlen_info
        slot_valid = aux_tensors[0]
        valid = utils.scalar_to_ssa(slot_valid[n_idx[0]], cutlass.Int32)
        zero = utils.scalar_to_ssa(0, cutlass.Int32)
        return valid != zero

    return valid_key


class Fa4Sm80Backend(base.Backend):
    """Patched FA4 SM80 kernels with a dense block mask."""

    def __init__(self, family: str):
        self.name = f'fa4-{family}'
        self.display = f'FA4 ({family.upper()})'

    def attend(self, q, k, v, block_mask, layout):
        _, _, block_sparsity, interface, _ = _modules()
        tensors = block_sparsity.DenseBlockMaskTorch(
            block_mask=(block_mask & layout.kv_ok)[None],
            partial_kv_blocks=~layout.full_tile,
            block_size=(tiling.TILE_SIZE, tiling.TILE_SIZE))
        with _CALL_LOCK, torch.no_grad():
            out = interface.flash_attn_func(
                q[None], k[None], v[None], softmax_scale=q.shape[-1] ** -0.5,
                mask_mod=_valid_key_mask_mod(),
                aux_tensors=[layout.slot_valid],
                block_sparse_tensors=tensors)
        if isinstance(out, tuple):
            out = out[0]
        return out[0]

    def warmup_note(self) -> str:
        return 'compiling kernels for this GPU (first run only, ~10 s)'


def create(info) -> base.Backend:
    if info.kind != 'cuda' or info.cc is None or info.cc[0] != _MAJOR:
        raise base.BackendUnavailable('fa4-sm80 is for SM80-family GPUs')
    try:
        _modules()
    except ImportError as error:
        raise base.BackendUnavailable(
            f'FA4 kernels are not installed ({error}); run install_fa4 to '
            'enable them') from error
    return Fa4Sm80Backend(info.family)
